model:
  model_name: nesymres
  checkpoint_path:  run/True/2021-05-30/17-58-53/Exp_weights/100000000_log_-epoch=02-val_loss=0.48.ckpt  
  beam_size: 2
  bfgs: True
  bfgs_n_restarts: 2
  complexity_reg_coef: 0.001
  train_bfgs: 0.5

  architecture:
    sinuisodal_embeddings: False
    dec_pf_dim: 512
    dec_layers: 5
    dim_hidden: 512  
    lr: 0.0001
    dropout: 0
    num_features: 10
    ln: True
    N_p: 0
    num_inds: 50
    activation: "relu"
    bit16: True
    norm: True
    linear: False
    input_normalization: False
    src_pad_idx: 0
    trg_pad_idx: 0
    length_eq: 60
    n_l_enc: 5
    mean: 0.5  
    std: 0.5 
    dim_input: 4
    num_heads: 8
    output_dim: 60
