train_path: data/datasets/20M/hdf_train
val_path: data/datasets/20M/hdf_val_subset
test_path: data/datasets/20M/hdf_val_subset

wandb: False
num_of_workers: 64
batch_size: 128
epochs: 200
val_check_interval: 0.2
precision: 16

dataset_train:
  total_variables: #Do not fill
  total_coefficients: #Do not fill
  max_number_of_points: 2000
  type_of_sampling_points: logarithm
  predict_c: False
  fun_support:
    max: 10
    min: -10
  constants:
    num_constants: 3
    additive:
      max: 2
      min: -2
    multiplicative:
      max: 5
      min: 0.1

dataset_val:
  total_variables: #Do not fill
  total_coefficients: #Do not fill
  max_number_of_points: 500
  type_of_sampling_points: constant
  predict_c: False
  fun_support:
    max: 10
    min: -10
  constants:
    num_constants: 3
    additive:
      max: 2
      min: -2
    multiplicative:
      max: 5
      min: 0.1

dataset_test:
  total_variables: #Do not fill
  total_coefficients: #Do not fill
  max_number_of_points: 500
  type_of_sampling_points: constant
  predict_c: False
  fun_support:
    max: 10
    min: -10
  constants:
    num_constants: 3
    additive:
      max: 2
      min: -2
    multiplicative:
      max: 5
      min: 0.1

architecture:
  sinuisodal_embeddings: False
  dec_pf_dim: 512
  dec_layers: 2
  dim_hidden: 512  
  lr: 0.0001
  dropout: 0
  num_features: 10
  ln: True
  N_p: 0
  num_inds: 50
  activation: "relu"
  bit16: True
  norm: True
  linear: False
  input_normalization: False
  src_pad_idx: 0
  trg_pad_idx: 0
  length_eq: 60
  n_l_enc: 2
  mean: 0.5  
  std: 0.5 
  dim_input: 4
  num_heads: 8
  output_dim: 60
  dropout: 0

# @package _group_
hydra:
  run:
    dir: run/${dataset_train.predict_c}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
      dir: runs/${dataset_train.predict_c}/${now:%Y-%m-%d}/${now:%H-%M-%S}