train_path: data/datasets/20M/hdf_train
val_path: data/datasets/20M/hdf_val_subset
num_of_workers: 64


dataset_train:
  max_number_of_points: 2000
  type_of_sampling_points: logarithm
  predict_c: True

dataset_val:
  max_number_of_points: 500
  type_of_sampling_points: constant
  predict_c: True